In [1]:
import pandas as pd
import numpy as np

In [2]:
book_data = pd.read_csv("Amazon_BestSelling_Books_500.csv")

In [4]:
book_data.head(3)

,Rank,Title,Author,Category,Sub-Genre,Format,Price (USD),Rating,Reviews,Weeks on List,Publisher,Year Published,ISBN,Amazon BSR,Amazon URL
0,1,The Let Them Theory,Mel Robbins,Non-Fiction,Self-Help,Paperback,14.99,4.7,98000.0,52.0,Hay House,2024.0,978-1-13278-859-4,112.0,View
1,2,The Dinner Party,Freida McFadden,Fiction,Psychological Thriller,Paperback,11.69,4.3,1800.0,12.0,Sourcebooks Landmark,2025.0,978-3-76237-716-0,175.0,View
2,3,Project Hail Mary,Andy Weir,Fiction,Science Fiction,Paperback,12.99,4.8,130000.0,108.0,Ballantine Books,2021.0,978-4-30379-320-5,64.0,View

In [5]:
book_data.nunique()

Rank              500
Title             500
Author            168
Category            2
Sub-Genre          48
Format              5
Price (USD)       439
Rating             15
Reviews           480
Weeks on List      73
Publisher          56
Year Published     21
ISBN              500
Amazon BSR        486
Amazon URL          1
dtype: int64

In [14]:
book_data.groupby("Format").max()

,Rank,Title,Author,Category,Sub-Genre,Price (USD),Rating,Reviews,Weeks on List,Publisher,Year Published,ISBN,Amazon BSR,Amazon URL
Format,,,,,,,,,,,,,,
Audiobook,490,World and Rain,various,Non-Fiction,YA Romance,34.09,4.9,43995.0,53.0,Zondervan,2026.0,978-9-68226-186-8,8600.0,View
Board Book,496,Weakness Code,Tomi Adeyemi,Non-Fiction,YA Romance,14.97,4.8,37524.0,46.0,Zondervan,2026.0,978-9-73997-140-5,9310.0,View
Hardcover,500,World and Bone,various,Non-Fiction,YA Romance,29.95,5.0,87363.0,1200.0,Zondervan,2026.0,978-9-98686-656-6,9475.0,View
Kindle Edition,499,World Unbound,various,Non-Fiction,YA Romance,12.49,5.0,41844.0,48.0,Zondervan,2026.0,978-9-90272-182-8,9600.0,View
Paperback,498,Window and Thunder,various,Non-Fiction,YA Romance,24.99,5.0,220000.0,400.0,Zondervan,2026.0,978-9-99727-823-0,8974.0,View

In [15]:
sample_data = book_data.sample(frac=0.2)

In [17]:
print(book_data.shape)
print(sample_data.shape)

(500, 15)
(100, 15)

In [19]:
#concat iki data seti birlestirmeye yarar
new_data_set = pd.concat([sample_data,book_data])
new_data_set.shape

(600, 15)

In [21]:
data = book_data[["Rank","Author","Category","Sub-Genre","Format","Rating","Publisher"]]

In [34]:
data.sort_values("Rating",ascending=False)

,Rank,Author,Category,Sub-Genre,Format,Rating,Publisher
207,208,Dean Koontz,Fiction,Horror,Kindle Edition,5.0,Doubleday
289,290,Susanna Clarke,Fiction,Paranormal Romance,Hardcover,5.0,Flatiron Books
403,404,Ta-Nehisi Coates,Non-Fiction,Personal Finance,Hardcover,5.0,Park Row
119,120,Virginia Evans,Fiction,Cozy Mystery,Paperback,5.0,Entangled: Red Tower Books
330,331,Jonathan Haidt,Non-Fiction,Celebrity Memoir,Hardcover,5.0,Rodale Books
...,...,...,...,...,...,...,...
310,311,Joyce Meyer,Non-Fiction,Self-Help,Paperback,3.7,Lioncrest Publishing
451,452,Arianna Huffington,Non-Fiction,Personal Finance,Paperback,3.7,Hay House
79,80,Seth Godin,Non-Fiction,Activity / Coloring,Audiobook,3.7,Tor Books
65,66,Doris Kearns Goodwin,Non-Fiction,Cooking / Food,Hardcover,3.7,"Little, Brown"
393,394,Malcolm Gladwell,Non-Fiction,Personal Finance,Paperback,3.6,Knopf

## Merge

In [73]:
test_data_1 = pd.DataFrame({"Sinif":["A","B","C","D"],
              "Not" : ["40","80","70","90"]
             })
test_data_1

  Sinif Not
0     A  40
1     B  80
2     C  70
3     D  90

In [77]:
test_data_2 = pd.DataFrame({"Sinif":["A","B","C","E"],
              "ogrenci_adi" : ["Can","Buse","Pelin","Semih"]
             })
test_data_2

  Sinif ogrenci_adi
0     A         Can
1     B        Buse
2     C       Pelin
3     E       Semih

In [78]:
#indicator nasil birlestiklerini anlatiyor
test_data_1.merge(test_data_2, on ="Sinif",how="outer",indicator=True)

  Sinif  Not ogrenci_adi      _merge
0     A   40         Can        both
1     B   80        Buse        both
2     C   70       Pelin        both
3     D   90         NaN   left_only
4     E  NaN       Semih  right_only

In [42]:
data_1 = data.query("Author == 'Dean Koontz' & Format =='Paperback'")

In [57]:
data_2 = data.query("Author == 'Dean Koontz' & Format =='Hardcover'")

In [59]:
# Merge icinde on hangi data uzerinden merge edilecegi belirler
data_1.merge(data_2,on="Author")

,Rank_x,Author,Category_x,Sub-Genre_x,Format_x,Rating_x,Publisher_x,Rank_y,Category_y,Sub-Genre_y,Format_y,Rating_y,Publisher_y
0,284,Dean Koontz,Fiction,Cozy Mystery,Paperback,4.2,Park Row,435,Fiction,Crime / Detective,Hardcover,4.6,Simon & Schuster
1,468,Dean Koontz,Fiction,Science Fiction,Paperback,4.7,Anchor Books,435,Fiction,Crime / Detective,Hardcover,4.6,Simon & Schuster

In [61]:
pd.concat([data_1,data_2])

,Rank,Author,Category,Sub-Genre,Format,Rating,Publisher
283,284,Dean Koontz,Fiction,Cozy Mystery,Paperback,4.2,Park Row
467,468,Dean Koontz,Fiction,Science Fiction,Paperback,4.7,Anchor Books
434,435,Dean Koontz,Fiction,Crime / Detective,Hardcover,4.6,Simon & Schuster

In [79]:
#Identifying missing data
#isnull show which data missing
is_null_data = pd.DataFrame({"A":[2,3,4,np.nan],
                            "B":[2,3,np.nan,np.nan],
                            "C":[np.nan,2,5,6]})

In [85]:
is_null_data.isnull().sum()

A    1
B    2
C    1
dtype: int64

In [90]:
#data nin yuzde kaci eksik
is_null_data.isnull().mean()

A    0.25
B    0.50
C    0.25
dtype: float64

In [103]:
is_null_data.dropna(subset=["C"])

     A    B    C
1  3.0  3.0  2.0
2  4.0  NaN  5.0
3  NaN  NaN  6.0

In [101]:
is_null_datais_null_data.isnull().index

Empty DataFrame
Columns: [A, B, C]
Index: []

In [105]:
book_data.dtypes

Rank                int64
Title              object
Author             object
Category           object
Sub-Genre          object
Format             object
Price (USD)       float64
Rating            float64
Reviews           float64
Weeks on List     float64
Publisher          object
Year Published    float64
ISBN               object
Amazon BSR        float64
Amazon URL         object
dtype: object

In [113]:
book_data.sort_values("Reviews", ascending=False)[["Title", "Author", "Reviews", "Rating"]].head(10)

                                  Title               Author   Reviews  Rating
26                      It Ends with Us       Colleen Hoover  220000.0     4.3
45                    Rich Dad Poor Dad      Robert Kiyosaki  180000.0     4.7
28                               Verity       Colleen Hoover  150000.0     4.5
33    The Seven Husbands of Evelyn Hugo  Taylor Jenkins Reid  145000.0     4.6
2                     Project Hail Mary            Andy Weir  130000.0     4.8
27                            Ugly Love       Colleen Hoover  130000.0     4.2
4                         Atomic Habits          James Clear  120000.0     4.8
46  The Subtle Art of Not Giving a F*ck          Mark Manson  115000.0     4.5
32                 Lessons in Chemistry        Bonnie Garmus  105000.0     4.5
0                   The Let Them Theory          Mel Robbins   98000.0     4.7

In [116]:
book_data.sort_values("Reviews", ascending=False)

,Rank,Title,Author,Category,Sub-Genre,Format,Price (USD),Rating,Reviews,Weeks on List,Publisher,Year Published,ISBN,Amazon BSR,Amazon URL
26,27,It Ends with Us,Colleen Hoover,Fiction,Contemporary Romance,Paperback,10.49,4.3,220000.0,200.0,Atria Books,2016.0,978-8-63264-735-2,1305.0,View
45,46,Rich Dad Poor Dad,Robert Kiyosaki,Non-Fiction,Personal Finance,Paperback,12.99,4.7,180000.0,400.0,Plata Publishing,1997.0,978-1-66822-470-7,2641.0,View
28,29,Verity,Colleen Hoover,Fiction,Psychological Thriller,Paperback,11.49,4.5,150000.0,120.0,Grand Central Publishing,2022.0,978-5-46517-985-1,4757.0,View
33,34,The Seven Husbands of Evelyn Hugo,Taylor Jenkins Reid,Fiction,Historical Fiction,Paperback,11.99,4.6,145000.0,120.0,Washington Square Press,2017.0,978-9-53933-195-3,3396.0,View
2,3,Project Hail Mary,Andy Weir,Fiction,Science Fiction,Paperback,12.99,4.8,130000.0,108.0,Ballantine Books,2021.0,978-4-30379-320-5,64.0,View
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368,369,The War of Roses,Terry Pratchett,Fiction,Space Opera,Paperback,11.90,4.8,148.0,7.0,Knopf,2018.0,978-1-96240-934-4,6062.0,View
484,485,Storm City,Matthew Stover,Fiction,Horror,Hardcover,28.40,4.7,115.0,4.0,Hoover Ink,2016.0,978-3-98257-300-4,8672.0,View
480,481,The Letter Unbound,Mary Kubica,Fiction,Crime / Detective,Kindle Edition,12.24,4.5,113.0,10.0,WaterBrook,2023.0,978-7-59725-428-7,3857.0,View
398,399,The Empire of Glass,Mark Manson,Non-Fiction,Politics / Society,Audiobook,32.84,4.4,98.0,10.0,Sourcebooks Landmark,2022.0,978-5-24046-105-5,3848.0,View
343,344,The Moon of Roses,Octavia Butler,Fiction,YA Romance,Audiobook,27.17,4.4,85.0,15.0,Atria Books,2010.0,978-6-82848-813-7,6934.0,View