In [3]:
import pandas as pd 
import numpy as np

In [5]:
veri = pd.Series(["ali","efe","ali","ali"]*3)
veri

0     ali
1     efe
2     ali
3     ali
4     ali
5     efe
6     ali
7     ali
8     ali
9     efe
10    ali
11    ali
dtype: object

In [6]:
pd.unique(veri)

array(['ali', 'efe'], dtype=object)

In [12]:

pd.Series(veri).value_counts()

ali    9
efe    3
Name: count, dtype: int64

In [8]:
degerler = pd.Series([0,1,0,0]*3)

In [10]:
adlar = pd.Series(["ali","efe"]) 
adlar.take(degerler)

0    ali
1    efe
0    ali
0    ali
0    ali
1    efe
0    ali
0    ali
0    ali
1    efe
0    ali
0    ali
dtype: object

In [13]:
N = len(veri)

In [14]:
df = pd.DataFrame({"isim":veri,
                  "no":np.arange(N),
                  "not":np.random.randint(40,100,size= N),
                  "kilo":np.random.uniform(50,70,size = N) },
                 columns = ["no","isim","not","kilo"])
df

    no isim  not       kilo
0    0  ali   59  61.835942
1    1  efe   73  64.197582
2    2  ali   43  58.546048
3    3  ali   47  57.744122
4    4  ali   77  62.581294
5    5  efe   41  64.630466
6    6  ali   43  57.406103
7    7  ali   54  69.726665
8    8  ali   76  65.078641
9    9  efe   80  67.278603
10  10  ali   68  61.788172
11  11  ali   91  51.193237

In [15]:
df["isim"]

0     ali
1     efe
2     ali
3     ali
4     ali
5     efe
6     ali
7     ali
8     ali
9     efe
10    ali
11    ali
Name: isim, dtype: object

In [17]:
type(df["isim"])

pandas.core.series.Series

In [18]:
isim_kat = df["isim"].astype("category")

In [20]:
isim_kat

0     ali
1     efe
2     ali
3     ali
4     ali
5     efe
6     ali
7     ali
8     ali
9     efe
10    ali
11    ali
Name: isim, dtype: category
Categories (2, object): ['ali', 'efe']

In [21]:
x= isim_kat.values

In [22]:
x.categories

Index(['ali', 'efe'], dtype='object')

In [23]:
x.codes

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [24]:
insanlar = ["bebek","cocuk","genc","yasli"]
kodlar = [0,1,2,3,1,0,0]
insan_kat = pd.Categorical.from_codes(kodlar,insanlar)
insan_kat

['bebek', 'cocuk', 'genc', 'yasli', 'cocuk', 'bebek', 'bebek']
Categories (4, object): ['bebek', 'cocuk', 'genc', 'yasli']

In [25]:
insan_kat = pd.Categorical.from_codes(kodlar,insanlar,ordered= True)
insan_kat

['bebek', 'cocuk', 'genc', 'yasli', 'cocuk', 'bebek', 'bebek']
Categories (4, object): ['bebek' < 'cocuk' < 'genc' < 'yasli']

In [26]:
insan_kat.as_ordered()

['bebek', 'cocuk', 'genc', 'yasli', 'cocuk', 'bebek', 'bebek']
Categories (4, object): ['bebek' < 'cocuk' < 'genc' < 'yasli']

In [27]:
data = np.random.randn(1000)

In [28]:
ara = pd.qcut(data,4)
ara

[(-3.022, -0.729], (-0.729, 0.00792], (0.00792, 0.718], (-3.022, -0.729], (0.718, 2.905], ..., (0.718, 2.905], (0.00792, 0.718], (0.00792, 0.718], (0.718, 2.905], (-3.022, -0.729]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.022, -0.729] < (-0.729, 0.00792] < (0.00792, 0.718] < (0.718, 2.905]]

In [29]:
type(ara)

pandas.core.arrays.categorical.Categorical

In [30]:
ara = pd.qcut(data,4,labels = ["Q!","Q2","Q3","Q4"])
ara

['Q!', 'Q2', 'Q3', 'Q!', 'Q4', ..., 'Q4', 'Q3', 'Q3', 'Q4', 'Q!']
Length: 1000
Categories (4, object): ['Q!' < 'Q2' < 'Q3' < 'Q4']

In [31]:
ara = pd.Series(ara,name="ceyrek")

In [44]:
pd.Series(data).groupby(ara, observed = False).agg(["count","min","max"]).reset_index()

  ceyrek  count       min       max
0     Q!    250 -3.020840 -0.731503
1     Q2    250 -0.728803  0.007272
2     Q3    250  0.008573  0.717490
3     Q4    250  0.717546  2.905496

In [36]:
N = 100000
say = pd.Series(np.random.randn(N))
etiket = pd.Series(["a","b","c","d"]*(N//4))
kat = etiket.astype("category")

In [37]:
etiket.memory_usage()

800132

In [38]:
kat.memory_usage()

100336

In [39]:
s = pd.Series(["a","b","c","d"]*2)
s_kat = s.astype("category")
s_kat

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [41]:
s_kat.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [42]:
s_kat.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [43]:
yeni_kat = ["a","b","c","d","e"]
s_kat.cat.set_categories(yeni_kat)

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']