# Panda

In [2]:
import pandas as pd 
import numpy as np

In [7]:
data = np.array([[1,4],[2,5],[3,6]])
df = pd.DataFrame(data,index =["row1","row2","row3"],
            columns=["col1","col2"])

In [8]:
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

In [16]:
data = [[1,4],[2,5],[3,6]]

In [17]:
df = pd.DataFrame(data,index =["row1","row2","row3"],
            columns=["col1","col2"])

In [18]:
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

In [22]:
iller = ['istanbul','adana','ankara','tekirdag']
plates = ["34","01","06","59"]

In [23]:
dict_iller = {"iller":iller, "plates": plates}

In [24]:
df_iller = pd.DataFrame(dict_iller)

In [33]:
df_iller.shape

(4, 2)

In [34]:
df_iller.info

<bound method DataFrame.info of       iller plates
0  istanbul     34
1     adana     01
2    ankara     06
3  tekirdag     59>

In [32]:
df_iller.iller

0    istanbul
1       adana
2      ankara
3    tekirdag
Name: iller, dtype: object