# Panda

In [2]:
import pandas as pd 
import numpy as np

In [7]:
data = np.array([[1,4],[2,5],[3,6]])
df = pd.DataFrame(data,index =["row1","row2","row3"],
            columns=["col1","col2"])

In [8]:
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

In [16]:
data = [[1,4],[2,5],[3,6]]

In [17]:
df = pd.DataFrame(data,index =["row1","row2","row3"],
            columns=["col1","col2"])

In [18]:
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

In [22]:
iller = ['istanbul','adana','ankara','tekirdag']
plates = ["34","01","06","59"]

In [23]:
dict_iller = {"iller":iller, "plates": plates}

In [24]:
df_iller = pd.DataFrame(dict_iller)

In [33]:
df_iller.shape

(4, 2)

In [34]:
df_iller.info

<bound method DataFrame.info of       iller plates
0  istanbul     34
1     adana     01
2    ankara     06
3  tekirdag     59>

In [32]:
df_iller.iller

0    istanbul
1       adana
2      ankara
3    tekirdag
Name: iller, dtype: object

In [44]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
population = np.random.randint(0,10000000, size = 4)

In [41]:
df_iller['Population'] = population

In [42]:
df_iller

      iller plates  Population
0  istanbul     34     4725480
1     adana     01     3519273
2    ankara     06     2043968
3  tekirdag     59     4873037

In [56]:
cars = np.random.randint(0,10000000, size = 4)
house = np.random.randint(0,10000000, size = 4)

np.int64(19247)

In [63]:
max(cars)

np.int64(9576759)

In [64]:
min(house)

np.int64(19247)

In [60]:
series1 = pd.Series(cars,index = np.arange(0,4))
series2 = pd.Series(house,index = np.arange(0,4))

In [61]:
df_iller = df_iller.assign(car_number = series1, house_number = series2)

In [62]:
df_iller

      iller plates  Population  car_number  house_number
0  istanbul     34     4725480     9576759         19247
1     adana     01     3519273     5312909       1925705
2    ankara     06     2043968      618222       2170996
3  tekirdag     59     4873037     3799845        343172

In [65]:
df_iller.insert(4,"test", series1)

In [67]:
df_iller.describe()

         Population    car_number          test  house_number
count  4.000000e+00  4.000000e+00  4.000000e+00  4.000000e+00
mean   3.790440e+06  4.826934e+06  4.826934e+06  1.114780e+06
std    1.312759e+06  3.722238e+06  3.722238e+06  1.090682e+06
min    2.043968e+06  6.182220e+05  6.182220e+05  1.924700e+04
25%    3.150447e+06  3.004439e+06  3.004439e+06  2.621908e+05
50%    4.122376e+06  4.556377e+06  4.556377e+06  1.134438e+06
75%    4.762369e+06  6.378872e+06  6.378872e+06  1.987028e+06
max    4.873037e+06  9.576759e+06  9.576759e+06  2.170996e+06